### ISSUE TITLE
Code Not Working

### ISSUE THREAD

**Issue by LeeBumSeok** [D3Mlab/count-style-transfer#1]
Hello,

I have recently read your paper and found it very insightful. I wanted to replicate the results for a deeper understanding, so I attempted to run the provided code. However, I encountered an issue where the code does not execute properly.

Could you please assist by looking into this matter? Any guidance on how to resolve the issue or an updated version of the code would be greatly appreciated.

**Comment by ssanner** [comment]
Thanks for your interest in this work!  Can you provide more detailed
information (including output logs) on the errors you are encountering?

**Comment by LeeBumSeok** [comment]
Thank you for your prompt response to assist!

Upon your request for more detailed information, I've outlined the specific issues I encountered while attempting to run eval_seq2seq_model.py:

1. The import statement from seq2seq.eval_checkpoint import paradetox_experiment fails because the paradetox_experiment function is missing, and I am unable to find it in the provided code.
2. There seems to be no alternative detoxifier code available besides Seq2SeqDetoxifier, which makes it impossible to import others as the documentation or code suggests.
3. The ParetoLogitsProcessor class is also missing from the provided files, preventing any form of import.
4. Similarly, I could not find the scalarizers code mentioned, making it impossible to import as well.

Given these missing components, I'm unsure how to proceed with obtaining the detoxified text using the COUNT method as intended. Could you provide guidance on how these issues might be resolved or where I might find the missing code segments?

**Comment by ssanner** [comment]
The code author (Mahdi) has made some updates to remove unused imports.  He says he has tested it locally, so hopefully it works now.

**Comment by LeeBumSeok** [comment]
Thank you for updating the code. I appreciate your research.
